parameters:
  - name: ProjectOrSolutionPath
    type: string
  - name: Major
    type: number
  - name: Minor
    type: number

stages:
  - template: /Stages/build-dotnet-nuget.yml
    parameters:
      ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}
      Major: ${{ parameters.Major }}
      Minor: ${{ parameters.Minor }}
      Configuration: Debug
      SkipBuildArtifactPackagingAndPublication: true
