parameters:
  - name: ProjectOrSolutionPath
    type: string
  - name: Major
    type: number
    default: 1
  - name: Minor
    type: number
    default: 0

stages:
  - template: /Stages/net/build.yml
    parameters:
      ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}
      Major: ${{ parameters.Major }}
      Minor: ${{ parameters.Minor }}
      Configuration: Release
      GeneratePackageOnBuild: true
  - template: /Stages/net/publish-nuget-package.yml
