parameters:
  - name: ProjectOrSolutionPath
    type: string
  - name: Major
    type: number
  - name: Minor
    type: number
  - name: Configuration
    type: string
    values:
      - Debug
      - Release
  - name: GeneratePackageOnBuild
    type: boolean

stages:
  - stage: build
    displayName: "Build stage"
    variables:
      VersionBuild: 0
      VersionRevision: 0
      PrivateSigningKeyPath: ""
    jobs:
      - job: prepare
        displayName: "Prepare"
        steps:
          - checkout: none

          - template: /Steps/generate-build-number.yml
            parameters:
              Major: ${{ parameters.Major }}
              Minor: ${{ parameters.Minor }}

      - job: build
        displayName: "Compile, test, and pack"
        pool:
          vmImage: "windows-latest"
        dependsOn: prepare
        condition: succeeded()
        steps:
          - checkout: self
            submodules: true

          - template: /Steps/download-private-signing-key.yml

          - template: /Steps/dotnet-restore.yml
            parameters:
              ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}

          - template: /Steps/dotnet-build.yml
            parameters:
              ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}
              Configuration: ${{ parameters.Configuration }}
              Major: ${{ parameters.Major }}
              Minor: ${{ parameters.Minor }}

          - template: /Steps/dotnet-test.yml
            parameters:
              ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}
              Configuration: ${{ parameters.Configuration }}

          - ${{ if eq(parameters.GeneratePackageOnBuild, true) }}:
            - template: /Steps/dotnet-pack.yml
              parameters:
                Configuration: ${{ parameters.Configuration }}

            - template: /Steps/publish-build-artifact.yml
              parameters:
                Configuration: ${{ parameters.Configuration }}

      - job: analyzeCode
        displayName: "Analyze code"
        dependsOn: prepare
        condition: succeeded()
        pool:
          vmImage: "windows-latest"
        steps:
          - checkout: self
            submodules: true

          - template: /Steps/dotnet-restore.yml
            parameters:
              ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}

          - template: /Steps/analyze-code-with-resharper.yml
            parameters:
              ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}
              Configuration: ${{ parameters.Configuration }}
