parameters:
  - name: ProjectOrSolutionPath
    type: string
  - name: Major
    type: number
    default: 1
  - name: Minor
    type: number
    default: 0
  - name: Configuration
    type: string
    default: Release
    values:
      - Debug
      - Release
  - name: GeneratePackageOnBuild
    type: boolean
    default: true

stages:
  - stage: build
    displayName: "Build stage"
    jobs:
      - job: compile
        displayName: "Compile, test, and package"
        pool:
          vmImage: "windows-latest"
        variables:
          VersionBuild: 0
          VersionRevision: 0
        steps:
          - checkout: self
            submodules: true
          - template: /Steps/generate-build-number.yml
            parameters:
              Major: ${{ parameters.Major }}
              Minor: ${{ parameters.Minor }}

          - template: /Steps/msbuild-build-and-test.yml
            parameters:
              ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}
              Major: ${{ parameters.Major }}
              Minor: ${{ parameters.Minor }}
              Configuration: ${{ parameters.Configuration }}

          - template: /Steps/resharper-code-analysis.yml
            parameters:
              ProjectOrSolutionPath: ${{ parameters.ProjectOrSolutionPath }}
              Configuration: ${{ parameters.Configuration }}

          - ${{ if eq(parameters.GeneratePackageOnBuild, true) }}:
            - template: /Steps/dotnet-pack-and-publish-artificat.yml