stages:
  - stage: publish
    displayName: "Publish stage"
    dependsOn: build
    condition: succeeded()
    jobs:
      - job: publish
        displayName: "Create github release and publish package on nuget.org"
        steps:
          - task: GitHubRelease@1
            displayName: create github release
            inputs:
              gitHubConnection: "github.com_icraftsoftware"
              repositoryName: "$(Build.Repository.Name)"
              action: "create"
              target: "$(Build.SourceVersion)"
              tagSource: "userSpecifiedTag"
              tag: "v$(Build.BuildNumber)"
              title: "$(Build.BuildNumber)"
              changeLogCompareToRelease: "lastFullRelease"
              changeLogType: "commitBased"
          - task: DownloadBuildArtifacts@0
            displayName: download nuget package artifact
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "nugetPackage"
              downloadPath: "$(System.ArtifactsDirectory)"
          - task: NuGetCommand@2
            displayName: nuget push
            inputs:
              command: "push"
              packagesToPush: "$(System.ArtifactsDirectory)/**/*.nupkg"
              nuGetFeedType: "external"
              publishFeedCredentials: "nuget.org_be.stateless"
              verbosityPush: "Normal"
